modLoader="javafml" 
loaderVersion="[28,)"

issueTrackerURL="https://github.com/KingVampyre/DeepTrenchesRepository/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="deep_trenches"
version="1.0.0-alpha"
displayName="Deep Trenches"
authors="KingVampire and Louwind"

# updateJSONURL="https://github.com/KingVampyre/DeepTrenchesRepository/issues"

# URL homepage
displayURL="https://github.com/KingVampyre/DeepTrenchesRepository/issues"

# A file name (in the root of the mod JAR)
logoFile=""

credits=""
description=''''''

[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
